# Tutorial Python
## Introdução Numpy
* https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html
* https://medium.com/programadores-ajudando-programadores/brincando-com-numpy-parte-1-vetores-vs-listas-51f4867ea0f1
* https://www.geeksforgeeks.org/python-lists-vs-numpy-arrays/

In [3]:
import numpy as np

In [3]:
# cria uma matriz unidimensional
mt = np.array([12,34,26,18,10])
print(mt)
print(type(mt))

[12 34 26 18 10]
<class 'numpy.ndarray'>


In [4]:
#Return evenly spaced values within a given interval.
mt = np.arange(1,5)             
print(mt)

[1 2 3 4]


In [19]:
#criar o array com um tipo específico
# cria o array como float e int
mtfloat = np.array([1, 2, 3], dtype = float)
print(mtfloat)
print(type(mtfloat))
mtint = np.array([1, 2, 3], dtype = int)
print(mtint)
print(type(mtint))

[1. 2. 3.]
<class 'numpy.ndarray'>
[1 2 3]
<class 'numpy.ndarray'>


In [18]:
#mudar o tipo do array
# Podemos transformar tipos de dados de arrays
mtnew = np.array([1.4, 3.6, -5.1, 9.42, 4.999999], dtype = float)
print(mtnew)
# quando transformamos de float para int os valores são truncados
mtnewint = mtnew.astype(int)
print(mtnewint)

[ 1.4       3.6      -5.1       9.42      4.999999]
[ 1  3 -5  9  4]


In [17]:
# podemos fazer o inverso também.
mt5 = np.array([1, 2, 3, 4])
print(mt5)
mt6 = mt5.astype(float)
print(mt6)

[1 2 3 4]
[1. 2. 3. 4.]


In [6]:
# mais de uma dimensão
# cria um matriz bidimensional
mt7 = np.array([[7,2,23],[12,27,4],[5,34,23]])
print(mt7)

[[ 7  2 23]
 [12 27  4]
 [ 5 34 23]]


In [7]:
# Numpy array a partir de uma lista
lst = [1,2,3,4,5,6]
arr = np.array(lst)
print(lst)
print(arr)

[1, 2, 3, 4, 5, 6]
[1 2 3 4 5 6]


In [7]:
#criar arrays vazios tipificados
#empty significa que não são inicializados, não que são vazios
vazio = np.empty([3,2], dtype = int)
print(vazio)
print("-------")
# cria uma matriz 4x3 com valores zero
zeros = np.zeros([4,3])
print(zeros)
print("-------")
#com valores igual a um
um = np.ones([5,7])
print(um)
print("-------")
# cria matriz quadrada com diagonal principal com valores 1 e os outros valores zero
diagonal = np.eye(5)
print(diagonal)


[[         0 1072693248]
 [         0 1073741824]
 [         0 1074266112]]
-------
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
-------
[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]
-------
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [11]:
#valores aleatórios entre zero e um
rnd = np.random.random((5))
print(rnd)
print("-------")
#valores aleatórios distr. normal contendo negativos
rnd2= np.random.randn((5))
print(rnd2)
print("-------")
# Valores inteiros aleatórios (3x5)
rnd3 = np.random.randint(100, size=(3, 5))
print(rnd3)

[0.54854309 0.62297663 0.66341944 0.58533999 0.20238602]
-------
[-1.94903903  0.36359026  0.22121146  0.92229898  0.50729057]
-------
[[73 66  2 70 47]
 [64 71 73 49 60]
 [ 6 94 94 34 12]]


In [34]:
#outra forma de gerar aleatórios
#uso de semente
gnr = np.random.default_rng(20)
rnd = gnr.random(3)
print (rnd)

#gerar inteiros
rnd = gnr.integers(10, size=(3, 4))
print(rnd)

[0.28007596 0.46114671 0.12171969]
[[2 5 2 4]
 [3 0 0 0]
 [6 9 9 6]]


In [22]:
#unique remove repetições
j = np.array([11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 18, 19, 20])
j = np.unique(j)
print(j)

[11 12 13 14 15 16 17 18 19 20]


In [23]:
#funções específicas
# cria a matriz bidimensional k
k = np.array([[17,22,43],[27,25,14],[15,24,32]])
# Mostra a matriz k
print(k)
# Mostra um elemento específico da matriz k
print(k[0][1])
# Mostra o tamanho das dimensões da matriz k
print(k.shape)

[[17 22 43]
 [27 25 14]
 [15 24 32]]
22
(3, 3)


In [24]:
#Funções Matemáticas
# Mostra o maior valor da matriz k
print(k.max())
# Mostra o menor valor da matriz k
print(k.min())
# Mostra a soma dos valores da matriz k
print((k.sum()))
# Mostra o valor da média dos valores da matriz k
print(k.mean())
# Mostra o valor do desvio padrão (standard deviation) dos valores da matiz k
print(k.std())

43
14
219
24.333333333333332
8.615231988880057


In [26]:
#extração de elementos
m = np.array([1, 2, 3, 4, 5, 6])
# Mostra o elemento da posição 2
print(m[1])
print("-------")
# Mostra o array criado a partir da posição 0, dois elementos
print(m[0:2])
print("-------")
# Mostra o array criado a partir da 2a posição
# até todo o restante do array
print(m[1:])
print("-------")
# Mostra o array criado a partir da antepenúltima
#posição até o final
print(m[-3:])

2
-------
[1 2]
-------
[2 3 4 5 6]
-------
[4 5 6]


In [38]:
#extração de linhas e colunas
mat = np.array([[4, 5], [6, 1], [7, 4]])
print(mat)
print("-------")
#primeira linha, todas as colunas
l1 = mat[0, :]
print(l1)
print("-------")
#segunda linha
l2 = mat[1, :]
print(l2)
print("-------")
#terceira linha
l3 = mat[2, :]
print(l3)
print("-------")
#todas as linhas, primeira coluna
c1 = mat[:, 0]
print(c1)
print("-------")
#todas as linhas, segunda coluna
c2 = mat[:, 1]
print(c2)

[[4 5]
 [6 1]
 [7 4]]
-------
[4 5]
-------
[6 1]
-------
[7 4]
-------
[4 6 7]
-------
[5 1 4]


In [60]:
# Redimensiona Matriz
rnd = np.arange(15).reshape((5, 3))
print(rnd)
print("-------")
# mostra a matriz com 5 linhas e 3 colunas
new_rnd = np.reshape(rnd, (3,5))
print(new_rnd)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
-------
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [73]:
# Cria um novo array com inserções no final
# Array original não é alterado
arr = np.array([[0,2,4],[6,8,10]]) 
app_arr = np.append(arr, [13,15,17]) 
print(app_arr)

[ 0  2  4  6  8 10 13 15 17]


In [70]:
print(arr)

[[ 0  2  4]
 [ 6  8 10]]


In [49]:
#expressões lógicas
#usando where
# criando matriz com valores aleatórios positivos e negativos
v = np.random.randn(4, 4)
print(v)
# criando matriz com valores booleanos baseado no array v
x = (v > 0)
print(x)
# criando matriz com valores -1 e 1 baseado nos valores do array x
z = np.where(x > 0, 1, -1)
print(z)


[[ 0.17260498 -0.04216884  0.59511135 -0.77303785]
 [ 1.47765185  0.99129444 -0.82405712 -2.19415029]
 [ 0.40905692 -0.88384692 -0.52981403 -1.11008486]
 [ 0.97403476 -1.6048133   0.96500133 -0.06919549]]
[[ True False  True False]
 [ True  True False False]
 [ True False False False]
 [ True False  True False]]
[[ 1 -1  1 -1]
 [ 1  1 -1 -1]
 [ 1 -1 -1 -1]
 [ 1 -1  1 -1]]
