1 - Escreva um código que converta uma lista (list) em um numpy array de 1 dimensão.

In [1]:
import numpy as np

lst = [1,2,3,4,5]
arr = np.array(lst)
print(arr)

[1 2 3 4 5]


2 - Escreva um código que crie uma matriz numpy (3x3) com valores variando de 2 a 10.

In [5]:
rnd = np.random.randint(2,11, size=(3, 3))
print(rnd)

[[10  7  5]
 [ 8  2  8]
 [ 8 10  4]]


3 - Crie um array Numpy com valores entre 12 a 38.

In [6]:
arr = np.random.randint(2,39, 10)
print(arr)

[ 7  5 36 15 38  5  6 31 33  7]


4 - Crie um array com 3 elementos inteiros. Após isso, usando o método append Numpy, faça a inclusão de mais 6 elementos no final do array inicial.
<br>
Ex:
<br>
Array inicial:
<br>
[10, 20, 30]
<br>
Inserir:
<br>
[40,50,60],[70,80,90]
<br>
Após as inserções:
<br>
[10 20 30 40 50 60 70 80 90]

In [8]:
arr=np.array([40,50,60])
att_arr = np.append(arr,([70,80,90],[100,102,103]) )
print(att_arr)

[ 40  50  60  70  80  90 100 102 103]


5 - Faça um código que altere a dimensão de um array Numpy:
<br>
Array inicial: [1 2 3 4 5 6 7 8 9]
<br>
Array Final:
<br>
[[1 2 3]
<br>
[4 5 6]
<br>
[7 8 9]]

In [10]:
arr= np.array([1,2,3,4,5,6,7,8,9])
new_arr=np.reshape(arr,(3,3))
print(new_arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


6 - Faça uma função que receba um array Numpy e retorne o valor máximo, mínimo e a soma de todos elementos.

In [13]:
def cond(arr_i):
    x = max(arr_i)
    y= min(arr_i)
    z=sum(arr_i)
    return x,y,z

arr=np.random.randint(10, 100, 12)
x,y,z = cond(arr)
print(x)
print(y)
print(z)

88
30
721


7 - Crie dois dicionários com as seguintes infromações:
<br>
Nome:Joao, RA:12345, Media:6.5
<br>
Telefone: 33334444, Email: joao@xyz.com
<br>
Crie um terceiro dicionário com a união dos dois dicionários anteriores.

In [15]:
dic1 = {'Nome': 'Joao', 'RA':12345, 'Media':6.5}
dic2= {'Telefone':33333344444, 'Email': 'joao@xyz.com'}

dic3={}
for key,values in zip(dic1.items(), dic2.items()):
    dic3[key]=values

print(dic3)

{('Nome', 'Joao'): ('Telefone', 33333344444), ('RA', 12345): ('Email', 'joao@xyz.com')}


In [16]:
dic4={}
dic4.update(dic1)
dic4.update(dic2)
print(dic4)

{'Nome': 'Joao', 'RA': 12345, 'Media': 6.5, 'Telefone': 33333344444, 'Email': 'joao@xyz.com'}
